// <auto-generated />
#nullable disable

using System;
using Games.Data;
using Games.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Games.Data.Migrations;

[DbContext(typeof(GameDbContext))]
[Migration("20260925001000_AddGameProperties")]
partial class AddGameProperties
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

        modelBuilder.Entity<Game>(b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("Genre")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<GameMode>("Mode")
                .HasColumnType("INTEGER");

            b.Property<string>("Name")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<DateTime>("ReleaseDate")
                .HasColumnType("TEXT");

            b.Property<long>("SoldCopies")
                .HasColumnType("INTEGER");

            b.Property<string>("Studio")
                .IsRequired()
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("Games");
        });
#pragma warning restore 612, 618
    }
}
